'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const actions=['BUILD','CHICKEN','PHOENIX','SKY_WHALE','WIN','ZAP','TNT','BLACK_HOLE','TORNADO','LOSE'];
const names={SKY_WHALE:'SKY WHALE',BLACK_HOLE:'BLACK HOLE',WIN:'+1 WIN',LOSE:'−1 WIN'};
function description(a){const n=cfg?.amounts?.[a]??1;if(a==='WIN')return `Ganha ${n} vitória(s)`;if(a==='LOSE')return `Perde ${n} vitória(s)`;return `${actions.indexOf(a)<5?'Constrói':'Destrói'} ${n} blocos`;}
let cfg, token, saveTimer, toastTimer, lastState, saving=false, dirty=false;
function toast(message,error=false){const e=$('#toast');e.textContent=message;e.className=error?'error':'';e.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.style.display='none',4500);}
async function api(path,body){const r=await fetch('/api/'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-B7-Token':token},body:body===undefined?undefined:JSON.stringify(body)});let data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Valor inválido. Confira os campos e limites.');return data;}
function get(path){return path.split('.').reduce((o,k)=>o[k],cfg);}
function set(path,val){let a=path.split('.'),o=cfg;for(const k of a.slice(0,-1))o=o[k];o[a.at(-1)]=val;}
function bindFields(root=document){root.querySelectorAll('[data-field]').forEach(e=>{const p=e.dataset.field;if(e.type==='checkbox')e.checked=get(p);else e.value=get(p);e.onchange=()=>{if(!e.checkValidity()){e.reportValidity();return;}set(p,e.type==='checkbox'?e.checked:['number','range'].includes(e.type)?Number(e.value):e.value);$$(`[data-field="${p}"]`).filter(x=>x!==e).forEach(x=>{if(x.type==='checkbox')x.checked=e.checked;else x.value=e.value;});scheduleSave();};});}
function scheduleSave(){$$('[data-description]').forEach(e=>e.textContent=description(e.dataset.description));dirty=true;$('#saved').textContent='Salvando…';clearTimeout(saveTimer);saveTimer=setTimeout(save,500);}
async function save(){if(saving||!dirty)return;saving=true;dirty=false;try{await api('settings',cfg);$('#saved').textContent='Configurações salvas';}catch(e){$('#saved').textContent='Alteração não salva';toast(e.message,true);}finally{saving=false;if(dirty)scheduleSave();}}
function options(selected){return actions.map(a=>`<option value="${a}" ${a===selected?'selected':''}>${names[a]||a} — ${description(a)}</option>`).join('');}
function mappingRows(){const box=$('#mappingRows');box.replaceChildren();$('#mappingEmpty').hidden=cfg.mappings.length>0;cfg.mappings.forEach((m,i)=>{const row=document.createElement('div');row.className='mapping';row.innerHTML='<input placeholder="ID do presente" aria-label="ID"><input placeholder="Nome exato (sem ID)" aria-label="Nome"><select aria-label="Ação">'+options(m.action)+'</select><button aria-label="Remover vínculo">×</button>';let fields=row.querySelectorAll('input,select');fields[0].value=m.gift_id;fields[1].value=m.gift_name;fields.forEach((e,k)=>e.onchange=()=>{m[['gift_id','gift_name','action'][k]]=e.value.trim();scheduleSave();});row.querySelector('button').onclick=()=>{cfg.mappings.splice(i,1);mappingRows();scheduleSave();};box.append(row);});}
function buildForms(){for(const a of actions){const card=document.createElement('label');card.className='action-item';card.innerHTML=`<img src="/assets/icon_${a}.png" alt="">${names[a]||a}<small class="effect-description" data-description="${a}">${description(a)}</small><input type="number" min="1" max="10000" data-field="amounts.${a}">`;$('#amounts').append(card);const b=document.createElement('button');b.innerHTML=`<img src="/assets/icon_${a}.png" alt="">${names[a]||a}<small class="effect-description" data-description="${a}">${description(a)}</small>`;b.onclick=()=>simulate(a);$('#testActions').append(b);}
for(const [key,title] of Object.entries({likes:'Curtidas',follows:'Novo seguidor',comments:'Comentário',shares:'Compartilhamento'})){const row=document.createElement('div');row.className='rule';row.innerHTML=`<label class="rule-title"><input type="checkbox" data-field="${key}.enabled">${title}</label><div class="form-grid"><label>Ação<select data-field="${key}.action">${options(cfg[key].action)}</select></label><label>Blocos/vitórias por ação<input type="number" min="1" max="1000" data-field="${key}.amount"></label><label>Intervalo por pessoa (s)<input type="number" min="0" max="3600" data-field="${key}.cooldown"></label>${key==='likes'?`<label>A cada X curtidas<input type="number" min="1" max="100000" data-field="${key}.threshold"></label>`:''}${key==='comments'?`<label>Palavra exata<input maxlength="80" data-field="${key}.word"></label>`:''}</div>`;$('#rules').append(row);}
bindFields();mappingRows();}
async function simulate(action='BUILD',kind='gift'){try{const count=Number($('#testCount').value);const r=await api('simulate',{action,kind,name:$('#testName').value,avatar:$('#testAvatar').value,count,combo:$('#testCombo').checked&&kind==='gift',comment:$('#testComment').value});const sum=r.applied.reduce((v,x)=>v+x.applied,0);const pending=r.applied.reduce((v,x)=>v+x.pending,0);toast(r.applied.length?`Aplicado: ${sum>0?'+':''}${sum}${pending?' · '+pending+' na fila':''}`:'Sem efeito: inicie a partida ou confira a regra/cooldown.');}catch(e){toast(e.message,true);}}
function update(s){lastState=s;$('#progress').textContent=s.progress+'%';$('#progressBar').style.width=s.progress+'%';$('#wins').textContent=`${s.wins} / ${s.goal}`;$('#round').textContent='Rodada '+s.round;$('#blocks').textContent=`${s.blocks} / ${s.capacity} blocos`;
$('#phase').textContent=!s.running?'Pausado':({building:'Construindo',defending:'Defesa '+Math.ceil(s.timer)+'s',celebrating:'Vitória!',goal:'Meta!'}[s.phase]||s.phase);
$('#modeBadge').textContent=s.config.mode==='test'?'MODO TESTE':'MODO LIVE';$('#modeBadge').className='badge '+(s.config.mode==='live'?'live':'');
const c=s.connection;$('#connectionBadge').textContent=({offline:'OFFLINE',connecting:'CONECTANDO',connected:'AO VIVO',reconnecting:'RECONECTANDO',error:'ERRO'}[c.status]||c.status);$('#connectionBadge').className='badge '+(c.status==='connected'?'live':'');$('#connectionMessage').textContent=c.message;$('#keyHint').textContent=s.key_saved?'Chave salva. Deixe o campo vazio para reutilizar.':'A chave fica protegida neste computador.';
$('#diagnostic').textContent=`${s.fps} FPS · Fila: ${s.queue} · Eventos recebidos: ${c.received}`;$('#notice').textContent=s.notice;$('#logs').textContent=s.logs.join('\n');
const cat=$('#catalog');if(s.catalog.length){cat.replaceChildren();s.catalog.forEach(g=>{const row=document.createElement('div');row.textContent=`${g.name} · ID ${g.id} `;const b=document.createElement('button');b.textContent='Vincular';b.onclick=()=>{cfg.mappings.push({gift_id:g.id,gift_name:g.name,action:'BUILD'});mappingRows();scheduleSave();};row.append(b);cat.append(row);});}}
function websocket(){const ws=new WebSocket(`ws://${location.host}/ws`);ws.onopen=()=>ws.send(JSON.stringify({token}));ws.onmessage=e=>update(JSON.parse(e.data));ws.onclose=()=>{setTimeout(websocket,1800);};ws.onerror=()=>{$('#connectionMessage').textContent='Painel reconectando ao jogo…';};}
async function init(){try{token=(await api('session')).token;const state=await api('state');cfg=state.config;$('#username').value=cfg.username;buildForms();update(state);websocket();}catch(e){toast('Não foi possível acessar o jogo: '+e.message,true);}}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));$('#pageTitle').textContent={home:'Visão geral',game:'Configurar jogo',interactions:'Interações',tests:'Modo de teste'}[b.dataset.tab];});
$$('[data-command]').forEach(b=>b.onclick=async()=>{try{await api('game/'+b.dataset.command,{});toast('Comando aplicado.');}catch(e){toast(e.message,true);}});
$('#connect').onclick=async()=>{const b=$('#connect');b.disabled=true;try{await api('connect',{username:$('#username').value,key:$('#key').value});$('#key').value='';cfg.username=$('#username').value;cfg.mode='live';bindFields();toast('Conexão iniciada.');}catch(e){toast(e.message,true);}finally{b.disabled=false;}};
$('#disconnect').onclick=async()=>{try{await api('disconnect',{});toast('Live desconectada.');}catch(e){toast(e.message,true);}};
$('#drop').onclick=async()=>{try{toast((await api('test-disconnect',{})).message);}catch(e){toast(e.message,true);}};
$('#addMapping').onclick=()=>{cfg.mappings.push({gift_id:'',gift_name:'',action:'BUILD'});mappingRows();};
$$('[data-event]').forEach(b=>b.onclick=()=>simulate('BUILD',b.dataset.event));init();
